apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /vol/data/
  volumes:
  - name: nginx-storage
    persistentVolumeClaim:
      claimName: nginx-pvc
